### PR TITLE
i replaced a singular placeholder image

### PR DESCRIPTION
**Pull request by lejshi3**
praise me

### CODE REVIEW

**Comment by garethyr** [comment]
Replace the title picture with Gotcha's please and thanks.

**Review by garethyr — CHANGES_REQUESTED** [review]
Replace the title picture with Gotcha's please and thanks.

**Comment by lejshi3** [comment]
done did that thing

**Comment by madgamer98** [comment]
Oh, that image was in the games files should have grabbed it from there originally then, I took the original file from the current data realms site and blew it up. I would also suggest someone put a class/id on that image and move the inline style into one of the stylesheet.

**Pull request merged**
